name: DEPLOY_MYDOCS
run-name: ${{github.workflow}}-${{github.job}}
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Debug workspace
        run: |
         pwd
         ls -la
         cd ./
         ls -la

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: pip install mkdocs-material
      - name: Build & Deploy Document
        run: |
          cd "$GITHUB_WORKSPACE"
          echo "Running mkdocs from: $(pwd)"
          mkdocs --version
          mkdocs gh-deploy --force


