name: DEPLOY_MYDOCS
run-name: ${{github.workflow}}-${{github.job}}
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Install Python & Dependencies
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          pip-install: -r requirements.txt
      - name: Build Document
        run: mkdocs gh-deploy --force


